///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PMI_MerchandisingPanel
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PMI_MerchandisingPanelRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("9c5ab078-be6d-4a9d-b835-15a4baba7c69")]
    public partial class PMI_MerchandisingPanelRepository : RepoGenBaseFolder
    {
        static PMI_MerchandisingPanelRepository instance = new PMI_MerchandisingPanelRepository();
        PMI_MerchandisingPanelRepositoryFolders.PmiMerchandisingPanelAppFolder _pmimerchandisingpanel;
        PMI_MerchandisingPanelRepositoryFolders.GoogleChromeDialogPopUpAppFolder _googlechromedialogpopup;

        /// <summary>
        /// Gets the singleton class instance representing the PMI_MerchandisingPanelRepository element repository.
        /// </summary>
        [RepositoryFolder("9c5ab078-be6d-4a9d-b835-15a4baba7c69")]
        public static PMI_MerchandisingPanelRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PMI_MerchandisingPanelRepository() 
            : base("PMI_MerchandisingPanelRepository", "/", null, 0, false, "9c5ab078-be6d-4a9d-b835-15a4baba7c69", ".\\RepositoryImages\\PMI_MerchandisingPanelRepository9c5ab078.rximgres")
        {
            _pmimerchandisingpanel = new PMI_MerchandisingPanelRepositoryFolders.PmiMerchandisingPanelAppFolder(this);
            _googlechromedialogpopup = new PMI_MerchandisingPanelRepositoryFolders.GoogleChromeDialogPopUpAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9c5ab078-be6d-4a9d-b835-15a4baba7c69")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PmiMerchandisingPanel folder.
        /// </summary>
        [RepositoryFolder("431641f4-c263-4d11-abaf-a7b4633fa7ef")]
        public virtual PMI_MerchandisingPanelRepositoryFolders.PmiMerchandisingPanelAppFolder PmiMerchandisingPanel
        {
            get { return _pmimerchandisingpanel; }
        }

        /// <summary>
        /// The GoogleChromeDialogPopUp folder.
        /// </summary>
        [RepositoryFolder("5e60c39c-baf1-439f-aadf-dd7b91dbe185")]
        public virtual PMI_MerchandisingPanelRepositoryFolders.GoogleChromeDialogPopUpAppFolder GoogleChromeDialogPopUp
        {
            get { return _googlechromedialogpopup; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class PMI_MerchandisingPanelRepositoryFolders
    {
        /// <summary>
        /// The PmiMerchandisingPanelAppFolder folder.
        /// </summary>
        [RepositoryFolder("431641f4-c263-4d11-abaf-a7b4633fa7ef")]
        public partial class PmiMerchandisingPanelAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _validate_loginscreenInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _panelsidebarInfo;
            RepoItemInfo _panelsidebar_listInfo;
            RepoItemInfo _abnormalityInfo;
            RepoItemInfo _abnormalityreportlistInfo;
            RepoItemInfo _merchandiservisitformInfo;
            RepoItemInfo _reporttypeInfo;
            RepoItemInfo _startdateInfo;
            RepoItemInfo _enddateInfo;
            RepoItemInfo _lastvisitInfo;
            RepoItemInfo _generatereportbuttonInfo;

            /// <summary>
            /// Creates a new PmiMerchandisingPanel  folder.
            /// </summary>
            public PmiMerchandisingPanelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PmiMerchandisingPanel", "/dom[@domain='mks.rtdtradetracker.com:1101']", parentFolder, 10000, null, false, "431641f4-c263-4d11-abaf-a7b4633fa7ef", "")
            {
                _validate_loginscreenInfo = new RepoItemInfo(this, "Validate_LoginScreen", ".//div[#'login']/section", 30000, null, "286f00e3-80ef-4273-ab07-fedaf5f204e1");
                _usernameInfo = new RepoItemInfo(this, "UserName", ".//input[#'userName']", 30000, null, "ebde827b-d22b-4800-914b-5ca918a4ce85");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "e9e2560f-96ef-426a-8728-7900a99e26d0");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//div[#'login']/?/?/form[@name='loginform']/input[@name='Submit']", 30000, null, "d66d4677-46fb-4fb8-9a6d-56779fb57cb5");
                _panelsidebarInfo = new RepoItemInfo(this, "PanelSideBar", ".//div[#'sidebar-menu']/div", 30000, null, "7f540051-e817-4f14-82f7-b6839a5671fc");
                _panelsidebar_listInfo = new RepoItemInfo(this, "PanelSideBar_List", ".//div[#'sidebar-menu']/?/?/ul", 30000, null, "9b844574-1529-4bb7-bae7-ce3caeae9dfe");
                _abnormalityInfo = new RepoItemInfo(this, "Abnormality", ".//div[#'sidebar-menu']/?/?/ul/?/?/a[@innertext='Abnormality']", 30000, null, "d0cb6531-b3a7-42c9-9698-3603ba7405de");
                _abnormalityreportlistInfo = new RepoItemInfo(this, "AbnormalityReportList", ".//div[#'sidebar-menu']/?/?/ul/?/?/ul/?/?/a[@innertext=' Abnormality Report List']", 30000, null, "42d19a3f-5f4c-4397-8f1b-ab7aed5ab80c");
                _merchandiservisitformInfo = new RepoItemInfo(this, "MerchandiserVisitForm", ".//form[#'merchandiserVisitForm']", 30000, null, "e756ceeb-c5ea-424e-97e6-477c7b2eb65e");
                _reporttypeInfo = new RepoItemInfo(this, "ReportType", ".//select[#'actionType']", 30000, null, "a5d65c61-0fdc-43c5-8252-f41c5d352bbe");
                _startdateInfo = new RepoItemInfo(this, "StartDate", ".//input[#'startDate']", 30000, null, "9d90c90d-5739-4ddf-903a-46d95fa93f1a");
                _enddateInfo = new RepoItemInfo(this, "EndDate", ".//input[#'endDate']", 30000, null, "d8162cc5-6ece-43a1-b9af-07d532ef52e0");
                _lastvisitInfo = new RepoItemInfo(this, "LastVisit", ".//select[#'lastVisit']", 30000, null, "2cffc806-eb91-4754-a967-25be28233fc7");
                _generatereportbuttonInfo = new RepoItemInfo(this, "GenerateReportButton", ".//input[#'btnId']", 30000, null, "c6f11200-cfef-401b-a222-c2548c66841b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("431641f4-c263-4d11-abaf-a7b4633fa7ef")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("431641f4-c263-4d11-abaf-a7b4633fa7ef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Validate_LoginScreen item.
            /// </summary>
            [RepositoryItem("286f00e3-80ef-4273-ab07-fedaf5f204e1")]
            public virtual Ranorex.SectionTag Validate_LoginScreen
            {
                get
                {
                    return _validate_loginscreenInfo.CreateAdapter<Ranorex.SectionTag>(true);
                }
            }

            /// <summary>
            /// The Validate_LoginScreen item info.
            /// </summary>
            [RepositoryItemInfo("286f00e3-80ef-4273-ab07-fedaf5f204e1")]
            public virtual RepoItemInfo Validate_LoginScreenInfo
            {
                get
                {
                    return _validate_loginscreenInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("ebde827b-d22b-4800-914b-5ca918a4ce85")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("ebde827b-d22b-4800-914b-5ca918a4ce85")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("e9e2560f-96ef-426a-8728-7900a99e26d0")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("e9e2560f-96ef-426a-8728-7900a99e26d0")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("d66d4677-46fb-4fb8-9a6d-56779fb57cb5")]
            public virtual Ranorex.InputTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("d66d4677-46fb-4fb8-9a6d-56779fb57cb5")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The PanelSideBar item.
            /// </summary>
            [RepositoryItem("7f540051-e817-4f14-82f7-b6839a5671fc")]
            public virtual Ranorex.DivTag PanelSideBar
            {
                get
                {
                    return _panelsidebarInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PanelSideBar item info.
            /// </summary>
            [RepositoryItemInfo("7f540051-e817-4f14-82f7-b6839a5671fc")]
            public virtual RepoItemInfo PanelSideBarInfo
            {
                get
                {
                    return _panelsidebarInfo;
                }
            }

            /// <summary>
            /// The PanelSideBar_List item.
            /// </summary>
            [RepositoryItem("9b844574-1529-4bb7-bae7-ce3caeae9dfe")]
            public virtual Ranorex.UlTag PanelSideBar_List
            {
                get
                {
                    return _panelsidebar_listInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The PanelSideBar_List item info.
            /// </summary>
            [RepositoryItemInfo("9b844574-1529-4bb7-bae7-ce3caeae9dfe")]
            public virtual RepoItemInfo PanelSideBar_ListInfo
            {
                get
                {
                    return _panelsidebar_listInfo;
                }
            }

            /// <summary>
            /// The Abnormality item.
            /// </summary>
            [RepositoryItem("d0cb6531-b3a7-42c9-9698-3603ba7405de")]
            public virtual Ranorex.ATag Abnormality
            {
                get
                {
                    return _abnormalityInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Abnormality item info.
            /// </summary>
            [RepositoryItemInfo("d0cb6531-b3a7-42c9-9698-3603ba7405de")]
            public virtual RepoItemInfo AbnormalityInfo
            {
                get
                {
                    return _abnormalityInfo;
                }
            }

            /// <summary>
            /// The AbnormalityReportList item.
            /// </summary>
            [RepositoryItem("42d19a3f-5f4c-4397-8f1b-ab7aed5ab80c")]
            public virtual Ranorex.ATag AbnormalityReportList
            {
                get
                {
                    return _abnormalityreportlistInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AbnormalityReportList item info.
            /// </summary>
            [RepositoryItemInfo("42d19a3f-5f4c-4397-8f1b-ab7aed5ab80c")]
            public virtual RepoItemInfo AbnormalityReportListInfo
            {
                get
                {
                    return _abnormalityreportlistInfo;
                }
            }

            /// <summary>
            /// The MerchandiserVisitForm item.
            /// </summary>
            [RepositoryItem("e756ceeb-c5ea-424e-97e6-477c7b2eb65e")]
            public virtual Ranorex.FormTag MerchandiserVisitForm
            {
                get
                {
                    return _merchandiservisitformInfo.CreateAdapter<Ranorex.FormTag>(true);
                }
            }

            /// <summary>
            /// The MerchandiserVisitForm item info.
            /// </summary>
            [RepositoryItemInfo("e756ceeb-c5ea-424e-97e6-477c7b2eb65e")]
            public virtual RepoItemInfo MerchandiserVisitFormInfo
            {
                get
                {
                    return _merchandiservisitformInfo;
                }
            }

            /// <summary>
            /// The ReportType item.
            /// </summary>
            [RepositoryItem("a5d65c61-0fdc-43c5-8252-f41c5d352bbe")]
            public virtual Ranorex.SelectTag ReportType
            {
                get
                {
                    return _reporttypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ReportType item info.
            /// </summary>
            [RepositoryItemInfo("a5d65c61-0fdc-43c5-8252-f41c5d352bbe")]
            public virtual RepoItemInfo ReportTypeInfo
            {
                get
                {
                    return _reporttypeInfo;
                }
            }

            /// <summary>
            /// The StartDate item.
            /// </summary>
            [RepositoryItem("9d90c90d-5739-4ddf-903a-46d95fa93f1a")]
            public virtual Ranorex.InputTag StartDate
            {
                get
                {
                    return _startdateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The StartDate item info.
            /// </summary>
            [RepositoryItemInfo("9d90c90d-5739-4ddf-903a-46d95fa93f1a")]
            public virtual RepoItemInfo StartDateInfo
            {
                get
                {
                    return _startdateInfo;
                }
            }

            /// <summary>
            /// The EndDate item.
            /// </summary>
            [RepositoryItem("d8162cc5-6ece-43a1-b9af-07d532ef52e0")]
            public virtual Ranorex.InputTag EndDate
            {
                get
                {
                    return _enddateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EndDate item info.
            /// </summary>
            [RepositoryItemInfo("d8162cc5-6ece-43a1-b9af-07d532ef52e0")]
            public virtual RepoItemInfo EndDateInfo
            {
                get
                {
                    return _enddateInfo;
                }
            }

            /// <summary>
            /// The LastVisit item.
            /// </summary>
            [RepositoryItem("2cffc806-eb91-4754-a967-25be28233fc7")]
            public virtual Ranorex.SelectTag LastVisit
            {
                get
                {
                    return _lastvisitInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The LastVisit item info.
            /// </summary>
            [RepositoryItemInfo("2cffc806-eb91-4754-a967-25be28233fc7")]
            public virtual RepoItemInfo LastVisitInfo
            {
                get
                {
                    return _lastvisitInfo;
                }
            }

            /// <summary>
            /// The GenerateReportButton item.
            /// </summary>
            [RepositoryItem("c6f11200-cfef-401b-a222-c2548c66841b")]
            public virtual Ranorex.InputTag GenerateReportButton
            {
                get
                {
                    return _generatereportbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GenerateReportButton item info.
            /// </summary>
            [RepositoryItemInfo("c6f11200-cfef-401b-a222-c2548c66841b")]
            public virtual RepoItemInfo GenerateReportButtonInfo
            {
                get
                {
                    return _generatereportbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The GoogleChromeDialogPopUpAppFolder folder.
        /// </summary>
        [RepositoryFolder("5e60c39c-baf1-439f-aadf-dd7b91dbe185")]
        public partial class GoogleChromeDialogPopUpAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _confimationpopupdialogInfo;
            RepoItemInfo _neverbuttonInfo;

            /// <summary>
            /// Creates a new GoogleChromeDialogPopUp  folder.
            /// </summary>
            public GoogleChromeDialogPopUpAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GoogleChromeDialogPopUp", "/form[@title~'^Do\\ you\\ want\\ Google\\ Chrome']", parentFolder, 10000, null, true, "5e60c39c-baf1-439f-aadf-dd7b91dbe185", "")
            {
                _confimationpopupdialogInfo = new RepoItemInfo(this, "ConfimationPopUpDialog", "container/container[1]", 100, null, "9facf0c1-4e94-44c2-b8e0-b9951620b098");
                _neverbuttonInfo = new RepoItemInfo(this, "NeverButton", "container/container[2]/?/?/button[@accessiblename='Never']", 100, null, "afb986c1-7b82-4ec0-92ed-964a3e2ce9d8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5e60c39c-baf1-439f-aadf-dd7b91dbe185")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5e60c39c-baf1-439f-aadf-dd7b91dbe185")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ConfimationPopUpDialog item.
            /// </summary>
            [RepositoryItem("9facf0c1-4e94-44c2-b8e0-b9951620b098")]
            public virtual Ranorex.Container ConfimationPopUpDialog
            {
                get
                {
                    return _confimationpopupdialogInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ConfimationPopUpDialog item info.
            /// </summary>
            [RepositoryItemInfo("9facf0c1-4e94-44c2-b8e0-b9951620b098")]
            public virtual RepoItemInfo ConfimationPopUpDialogInfo
            {
                get
                {
                    return _confimationpopupdialogInfo;
                }
            }

            /// <summary>
            /// The NeverButton item.
            /// </summary>
            [RepositoryItem("afb986c1-7b82-4ec0-92ed-964a3e2ce9d8")]
            public virtual Ranorex.Button NeverButton
            {
                get
                {
                    return _neverbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NeverButton item info.
            /// </summary>
            [RepositoryItemInfo("afb986c1-7b82-4ec0-92ed-964a3e2ce9d8")]
            public virtual RepoItemInfo NeverButtonInfo
            {
                get
                {
                    return _neverbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}